# Generated by Django 4.1.1 on 2022-09-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("author", models.CharField(max_length=100, null=True)),
                ("author_email", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=300, null=True)),
                ("keywords", models.CharField(max_length=200, null=True)),
                ("version", models.CharField(max_length=10, null=True)),
                ("maintainer", models.CharField(max_length=100, null=True)),
                ("maintainer_email", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
