# Generated by Django 4.1.1 on 2022-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=50, null=True)),
                ("link", models.CharField(max_length=100, null=True)),
                ("guid", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("author", models.CharField(max_length=50, null=True)),
                ("pubdate", models.DateField(null=True)),
            ],
        ),
    ]
